const PROTOCOL_ROUTER = 'tcp';
const ADDR_ROUTER = '192.168.171.132';
const PORT_ROUTER = '4242';
const PROTOCOL_PUB = 'tcp';
const ADDR_PUB = '192.168.171.132';
const PORT_PUB = '12345';
const IDENTITY_BASE = '#0x';
const RETRY = 5;

module.exports = {
  PROTOCOL_ROUTER,
  ADDR_ROUTER,
  PORT_ROUTER,
  PROTOCOL_PUB,
  ADDR_PUB,
  PORT_PUB,
  IDENTITY_BASE,
  RETRY,
};
